
import nodemailer from 'nodemailer';

interface EmailPayload {
  name: string;
  email: string;
  message: string;
  type?: 'contact' | 'transcript';
}

// Environment variables
const GMAIL_USER = process.env.GMAIL_USER;
const GMAIL_APP_PASSWORD = process.env.GMAIL_APP_PASSWORD;
const OWNER_EMAIL = "sayantanbiswas.mycareer@gmail.com"; // Your email

export default async (req: Request) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST',
        'Access-Control-Allow-Headers': 'Content-Type',
      }
    });
  }

  if (req.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 });
  }

  try {
    const body = await req.json() as EmailPayload;
    const userAgent = req.headers.get('user-agent') || 'Unknown';
    // Netlify headers for IP
    const ip = req.headers.get('x-nf-client-connection-ip') || req.headers.get('client-ip') || 'Unknown'; 
    
    if (!body.email || !body.message) {
      return new Response(JSON.stringify({ error: "Missing required fields" }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    const isTranscript = body.type === 'transcript';

    // --- DEMO MODE / FALLBACK ---
    if (!GMAIL_USER || !GMAIL_APP_PASSWORD) {
      console.log(`⚠️  GMAIL CREDENTIALS MISSING - RUNNING IN DEMO MODE (${isTranscript ? 'TRANSCRIPT' : 'CONTACT'})`);
      return new Response(JSON.stringify({ success: true, mode: 'demo' }), {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        }
      });
    }

    // --- CONFIGURATION ---
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: GMAIL_USER,
        pass: GMAIL_APP_PASSWORD,
      },
    });

    let mailOptions;

    if (isTranscript) {
      // CASE 1: SEND TRANSCRIPT TO USER
      const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head><meta charset="utf-8"><title>Chat Transcript</title></head>
      <body style="font-family: sans-serif; color: #333; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #eee; border-radius: 8px; padding: 20px;">
          <h2 style="color: #0f172a; margin-top: 0;">Chat Transcript</h2>
          <p style="color: #666; font-size: 14px;">Here is the copy of your conversation with Sayantan's AI Assistant.</p>
          
          <div style="background-color: #f8fafc; border-radius: 8px; padding: 15px; margin: 20px 0; font-size: 14px; line-height: 1.6; white-space: pre-wrap; border: 1px solid #e2e8f0;">${body.message}</div>

          <p style="font-size: 12px; color: #999; text-align: center;">Generated by Sayantan Biswas Portfolio AI</p>
        </div>
      </body>
      </html>
      `;

      mailOptions = {
        from: `"Sayantan's AI Assistant" <${GMAIL_USER}>`,
        to: body.email, // Send TO the user
        replyTo: OWNER_EMAIL, // If they reply, it goes to you
        subject: `Your Chat Transcript with Sayantan's AI`,
        text: body.message,
        html: htmlContent,
      };

    } else {
      // CASE 2: SEND CONTACT FORM TO OWNER
      const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head><meta charset="utf-8"><title>New Contact Message</title></head>
      <body style="font-family: sans-serif; line-height: 1.6; color: #333; padding: 20px;">
        <div style="max-width: 650px; margin: 0 auto;">
          <div style="border-bottom: 1px solid #e5e7eb; padding-bottom: 15px; margin-bottom: 25px;">
            <h2 style="color: #0f172a; margin: 0;">New Portfolio Contact</h2>
          </div>
          <p><strong>From:</strong> ${body.name} &lt;${body.email}&gt;</p>
          <div style="background-color: #f8fafc; border-left: 3px solid #0ea5e9; padding: 16px; margin: 20px 0; white-space: pre-wrap;">${body.message}</div>
          <div style="font-size: 12px; color: #64748b; border-top: 1px solid #eee; padding-top: 10px;">
            <strong>IP:</strong> ${ip} | <strong>UA:</strong> ${userAgent}
          </div>
        </div>
      </body>
      </html>
      `;

      mailOptions = {
        from: `"Portfolio Notification" <${GMAIL_USER}>`,
        to: OWNER_EMAIL, // Send TO you
        replyTo: body.email,
        subject: `Portfolio Inquiry: ${body.name}`,
        text: `Name: ${body.name}\nEmail: ${body.email}\nMessage:\n${body.message}`,
        html: htmlContent,
      };
    }

    const info = await transporter.sendMail(mailOptions);
    console.log("Message sent: %s", info.messageId);

    return new Response(JSON.stringify({ success: true, messageId: info.messageId }), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      }
    });

  } catch (error: any) {
    console.error("SMTP Error:", error);
    return new Response(JSON.stringify({ error: "Failed to send email", details: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
};
